namespace HmsAgents.Core.Models;

public enum WorkItemType { Epic, UserStory, UseCase, Task }

public enum WorkItemStatus
{
    New,        // Just generated by the expander
    InQueue,    // Queued for development iteration
    UnderDev,   // Being processed by pipeline agents
    Completed,  // Artifacts generated and reviewed
    Blocked     // Dependency not met
}

/// <summary>
/// Tracks how well a requirement is covered by generated artifacts.
/// </summary>
public enum CoverageStatus
{
    NotAssessed,    // Haven't checked yet
    NotStarted,     // No artifacts match this requirement
    Partial,        // Some artifacts exist but acceptance criteria not fully met
    Covered,        // All acceptance criteria have matching artifacts
    GapIdentified   // Analyzer found specific missing pieces
}

public sealed class ExpandedRequirement
{
    public string Id { get; init; } = string.Empty;
    public string ParentId { get; init; } = string.Empty;
    public string SourceRequirementId { get; init; } = string.Empty;
    public WorkItemType ItemType { get; init; }
    public WorkItemStatus Status { get; set; } = WorkItemStatus.New;
    public string Title { get; init; } = string.Empty;
    public string Description { get; init; } = string.Empty;
    public string Module { get; init; } = string.Empty;
    public int Priority { get; init; }
    public int Iteration { get; set; }
    public List<string> AcceptanceCriteria { get; init; } = [];
    public List<string> DependsOn { get; init; } = [];
    public List<string> Tags { get; init; } = [];
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
    public DateTimeOffset? StartedAt { get; set; }
    public DateTimeOffset? CompletedAt { get; set; }
    /// <summary>Which agent is currently working on (or completed) this item.</summary>
    public string AssignedAgent { get; set; } = string.Empty;

    // ── Gap-analysis fields (populated by RequirementAnalyzerAgent) ──
    /// <summary>Coverage assessment after artifact analysis.</summary>
    public CoverageStatus Coverage { get; set; } = CoverageStatus.NotAssessed;
    /// <summary>Specific gaps identified (e.g. "Missing RLS policy", "No unit tests for UpdateClaim").</summary>
    public List<string> IdentifiedGaps { get; set; } = [];
    /// <summary>Artifacts that implement (fully or partially) this requirement.</summary>
    public List<string> MatchingArtifactPaths { get; set; } = [];
    /// <summary>IDs of requirements that must be completed before this one can start.</summary>
    public List<string> ResolvedDependencyChain { get; set; } = [];
    /// <summary>Services/entities this requirement touches — guides downstream code-gen agents.</summary>
    public List<string> AffectedServices { get; set; } = [];
    /// <summary>Detailed specification for downstream agents (DB schema hints, API contracts, validation rules).</summary>
    public string DetailedSpec { get; set; } = string.Empty;
    /// <summary>Source: which agent created this item (Expander, Analyzer, Backlog).</summary>
    public string ProducedBy { get; set; } = string.Empty;
}
