using FluentAssertions;
using GNex.Agents.Orchestrator;
using GNex.Core.Enums;
using GNex.Core.Interfaces;
using GNex.Core.Models;
using Microsoft.Extensions.Logging;
using Moq;

namespace GNex.Tests;

public class OrchestratorTests
{
    private readonly Mock<IArtifactWriter> _writerMock = new();
    private readonly Mock<IPipelineEventSink> _sinkMock = new();
    private readonly Mock<IAuditLogger> _auditMock = new();
    private readonly Mock<ILlmProvider> _llmMock = new();
    private readonly Mock<IHumanGate> _humanGateMock = new();
    private readonly Mock<IServiceProvider> _serviceProviderMock = new();
    private readonly Mock<ILogger<AgentOrchestrator>> _loggerMock = new();

    public OrchestratorTests()
    {
        _llmMock.SetupGet(x => x.IsAvailable).Returns(true);
        _llmMock.SetupGet(x => x.ProviderName).Returns("test-llm");
        _llmMock
            .Setup(x => x.GenerateAsync(It.IsAny<LlmPrompt>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new LlmResponse
            {
                Success = true,
                Content = "objective\nsteps\nrisks",
                Model = "test-model"
            });
    }

    private PipelineConfig CreateConfig() => new()
    {
        RequirementsPath = Path.Combine(Path.GetTempPath(), "gnex-test-reqs"),
        OutputPath = Path.Combine(Path.GetTempPath(), "gnex-test-out"),
        SpinUpDocker = false,
        ExecuteDdl = false
    };

    private AgentOrchestrator CreateOrchestrator(List<IAgent> agents)
        => new(
            agents,
            _llmMock.Object,
            _writerMock.Object,
            _sinkMock.Object,
            _auditMock.Object,
            _humanGateMock.Object,
            _serviceProviderMock.Object,
            _loggerMock.Object);

    private static Mock<IAgent> CreateAgentMock(AgentType type, string name, bool success = true, int artifactCount = 3)
    {
        var mock = new Mock<IAgent>();
        mock.Setup(a => a.Type).Returns(type);
        mock.Setup(a => a.Name).Returns(name);
        mock.Setup(a => a.ExecuteAsync(It.IsAny<AgentContext>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((AgentContext ctx, CancellationToken _) =>
            {
                ctx.AgentStatuses[type] = success ? AgentStatus.Completed : AgentStatus.Failed;
                var artifacts = Enumerable.Range(0, artifactCount).Select(i => new CodeArtifact
                {
                    Layer = ArtifactLayer.Database,
                    RelativePath = $"{name}/{i}.cs",
                    FileName = $"{i}.cs",
                    Content = $"// Generated by {name}",
                    ProducedBy = type
                }).ToList();
                ctx.Artifacts.AddRange(artifacts);
                return new AgentResult
                {
                    Agent = type,
                    Success = success,
                    Summary = success ? $"{name} ok" : $"{name} failed",
                    Artifacts = artifacts
                };
            });
        return mock;
    }

    [Fact]
    public async Task RunPipeline_AllAgentsSucceed_CompletesSuccessfully()
    {
        var reqsDir = CreateConfig().RequirementsPath;
        Directory.CreateDirectory(reqsDir);
        File.WriteAllText(Path.Combine(reqsDir, "test.md"), "# REQ-001\nTest requirement");

        var agents = new List<IAgent>
        {
            CreateAgentMock(AgentType.RequirementsReader, "ReqReader").Object,
            CreateAgentMock(AgentType.Database, "Database").Object,
            CreateAgentMock(AgentType.ServiceLayer, "ServiceLayer").Object,
            CreateAgentMock(AgentType.Application, "Application").Object,
            CreateAgentMock(AgentType.Integration, "Integration").Object,
            CreateAgentMock(AgentType.Testing, "Testing").Object,
            CreateAgentMock(AgentType.Review, "Review").Object,
            CreateAgentMock(AgentType.Supervisor, "Supervisor").Object,
        };

        var orchestrator = CreateOrchestrator(agents);

        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(20));
        var result = await orchestrator.RunPipelineAsync(CreateConfig(), cts.Token);

        result.CompletedAt.Should().NotBeNull();
        result.Artifacts.Should().NotBeEmpty();
        result.AgentStatuses.Values.Where(s => s == AgentStatus.Completed).Should().HaveCountGreaterThan(0);
    }

    [Fact]
    public void GetCurrentContext_ReturnsNull_BeforePipelineRun()
    {
        var orchestrator = CreateOrchestrator([]);
        orchestrator.GetCurrentContext().Should().BeNull();
    }

    [Fact]
    public void RelevantTaskAgents_UsesDescriptionText_ForRouting()
    {
        var item = new ExpandedRequirement
        {
            Id = "TASK-001",
            ItemType = WorkItemType.Task,
            Title = "Implement persistence",
            Description = "Create SQL migration and update DbContext mappings for admissions",
            Tags = []
        };

        var method = typeof(AgentOrchestrator).GetMethod("GetRelevantTaskAgents", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
        method.Should().NotBeNull();

        var result = method!.Invoke(null, [item]) as List<string>;

        result.Should().NotBeNull();
        result!.Should().Contain(AgentType.Database.ToString());
    }
}
