using System.Text.RegularExpressions;
using GNex.Core.Enums;
using GNex.Core.Models;

namespace GNex.Agents.Requirements;

/// <summary>
/// Parses C# entity source code (from DatabaseAgent artifacts) to extract field definitions.
/// This allows downstream agents (ServiceLayer, Testing) to generate complete code
/// with proper DTO mappings, service implementations, and tests.
/// </summary>
public static partial class EntityFieldExtractor
{
    private static readonly HashSet<string> AuditFieldNames =
    [
        "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy", "VersionNo"
    ];

    private static readonly HashSet<string> NavigationTypes =
    [
        "ICollection", "IList", "IEnumerable", "List", "HashSet"
    ];

    /// <summary>
    /// Build a ParsedDomainModel from the active service catalog + entity artifacts generated by DatabaseAgent.
    /// </summary>
    public static ParsedDomainModel BuildDomainModel(List<CodeArtifact> artifacts, IReadOnlyList<MicroserviceDefinition>? services = null)
    {
        var model = new ParsedDomainModel();
        var catalog = services ?? [];

        if (catalog.Count == 0) return model;

        foreach (var svc in catalog)
        {
            foreach (var entityName in svc.Entities)
            {
                var entityArtifact = artifacts.FirstOrDefault(a =>
                    a.Layer == ArtifactLayer.Database &&
                    a.FileName == $"{entityName}.cs" &&
                    a.RelativePath.Contains(svc.ProjectName));

                var fields = entityArtifact is not null
                    ? ExtractFields(entityArtifact.Content)
                    : [];

                var parsed = new ParsedEntity
                {
                    Name = entityName,
                    ServiceName = svc.Name,
                    ServiceShortName = svc.ShortName,
                    Schema = svc.Schema,
                    Namespace = svc.Namespace,
                    DbContextName = svc.DbContextName,
                    Fields = fields,
                    NavigationProperties = fields.Where(f => f.IsNavigation).Select(f => f.Name).ToList(),
                    FeatureTags = InferFeatureTags(svc, entityName)
                };

                model.Entities.Add(parsed);

                // Generate API endpoint specs
                var kebab = ToKebabCase(entityName);
                model.ApiEndpoints.AddRange(
                [
                    new() { ServiceName = svc.Name, EntityName = entityName, Method = "GET", Path = $"/{kebab}/{{id}}", OperationName = $"Get{entityName}" },
                    new() { ServiceName = svc.Name, EntityName = entityName, Method = "GET", Path = $"/{kebab}", OperationName = $"List{entityName}s" },
                    new() { ServiceName = svc.Name, EntityName = entityName, Method = "POST", Path = $"/{kebab}", OperationName = $"Create{entityName}" },
                    new() { ServiceName = svc.Name, EntityName = entityName, Method = "PUT", Path = $"/{kebab}/{{id}}", OperationName = $"Update{entityName}" },
                ]);

                // Generate domain event specs
                model.DomainEvents.AddRange(
                [
                    new() { ServiceName = svc.Name, EntityName = entityName, EventName = $"{entityName}CreatedEvent", EventType = $"{svc.ShortName}.{ToSnakeCase(entityName)}.created", Topic = $"app.{svc.ShortName}.events" },
                    new() { ServiceName = svc.Name, EntityName = entityName, EventName = $"{entityName}UpdatedEvent", EventType = $"{svc.ShortName}.{ToSnakeCase(entityName)}.updated", Topic = $"app.{svc.ShortName}.events" },
                ]);
            }
        }

        // Feature mappings derived from service catalog
        model.FeatureMappings = BuildFeatureMappings(catalog);

        // NFR requirements
        model.NfrRequirements = BuildNfrRequirements();

        return model;
    }

    /// <summary>
    /// Extract fields from C# entity class source code.
    /// </summary>
    public static List<EntityField> ExtractFields(string entitySource)
    {
        var fields = new List<EntityField>();
        var lines = entitySource.Split('\n');

        foreach (var line in lines)
        {
            var trimmed = line.Trim();

            // Match property pattern: public Type Name { get; set; }
            var propMatch = PropertyRegex().Match(trimmed);
            if (!propMatch.Success) continue;

            var typeName = propMatch.Groups["type"].Value;
            var propName = propMatch.Groups["name"].Value;
            var defaultVal = propMatch.Groups["default"].Success ? propMatch.Groups["default"].Value.Trim() : null;

            // Check for [Key] and [Required] attributes on previous lines or same declaration context
            var isKey = trimmed.Contains("[Key]") || HasAttributeAbove(lines, line, "[Key]");
            var isRequired = trimmed.Contains("[Required]") || HasAttributeAbove(lines, line, "[Required]");
            var isNullable = typeName.EndsWith('?');
            var isNavigation = NavigationTypes.Any(n => typeName.Contains(n)) ||
                               (!typeName.StartsWith("string", StringComparison.Ordinal) &&
                                !IsBuiltInType(typeName) &&
                                !typeName.Contains("DateTimeOffset") &&
                                !typeName.Contains("DateOnly") &&
                                !typeName.Contains("decimal") &&
                                !typeName.EndsWith('?'));

            // Check if it's a collection navigation
            if (NavigationTypes.Any(n => typeName.StartsWith(n)))
                isNavigation = true;

            // Non-collection single entity navigation (e.g., public Patient Patient { get; set; })
            if (!isNavigation && char.IsUpper(typeName[0]) && !IsBuiltInType(typeName))
                isNavigation = true;

            fields.Add(new EntityField
            {
                Name = propName,
                Type = typeName,
                IsRequired = isRequired || isKey,
                IsKey = isKey,
                IsNullable = isNullable,
                DefaultValue = defaultVal,
                IsAuditField = AuditFieldNames.Contains(propName),
                IsNavigation = isNavigation
            });
        }

        return fields;
    }

    private static bool HasAttributeAbove(string[] lines, string currentLine, string attribute)
    {
        var idx = Array.IndexOf(lines, lines.FirstOrDefault(l => l == currentLine));
        if (idx <= 0) return false;
        var prev = lines[idx - 1].Trim();
        return prev.Contains(attribute);
    }

    private static bool IsBuiltInType(string type)
    {
        var clean = type.TrimEnd('?');
        return clean is "string" or "int" or "long" or "bool" or "decimal" or "double" or "float"
            or "byte" or "char" or "short" or "DateTimeOffset" or "DateOnly" or "DateTime"
            or "Guid" or "TimeSpan";
    }

    private static List<FeatureMapping> BuildFeatureMappings(IReadOnlyList<MicroserviceDefinition> catalog)
    {
        // Derive feature mappings dynamically from the service catalog
        var mappings = new List<FeatureMapping>();
        var featureIndex = 1;
        foreach (var svc in catalog)
        {
            mappings.Add(new FeatureMapping
            {
                FeatureId = $"EP-{featureIndex:D2}",
                Module = svc.ShortName.Length > 0 ? svc.ShortName[..1].ToUpperInvariant() : "X",
                FeatureName = svc.Description.Length > 0 ? svc.Description : svc.Name,
                ServiceNames = [svc.Name],
                EntityNames = [.. svc.Entities]
            });
            featureIndex++;
        }
        return mappings;
    }

    private static List<NfrRequirement> BuildNfrRequirements() =>
    [
        new() { Id = "NFR-SEC-01", Category = "Security", Description = "All entities must have TenantId for tenant isolation", ValidationRule = "entity_has_tenant_id" },
        new() { Id = "NFR-SEC-02", Category = "Security", Description = "RLS policies must exist for all regulated tables", ValidationRule = "rls_policy_exists" },
        new() { Id = "NFR-AUD-01", Category = "Audit", Description = "All entities must have audit columns (CreatedAt, CreatedBy)", ValidationRule = "entity_has_audit_columns" },
        new() { Id = "NFR-AUD-02", Category = "Audit", Description = "Create and Update operations must publish domain events", ValidationRule = "crud_publishes_events" },
        new() { Id = "NFR-DATA-01", Category = "DataGovernance", Description = "Sensitive entities must have ClassificationCode for data sensitivity", ValidationRule = "entity_has_classification" },
        new() { Id = "NFR-MT-01", Category = "MultiTenancy", Description = "DbContext must have HasQueryFilter for tenant isolation", ValidationRule = "dbcontext_has_query_filter" },
        new() { Id = "NFR-CODE-01", Category = "CodeQuality", Description = "No TODO comments in generated service implementations", ValidationRule = "no_todo_comments" },
        new() { Id = "NFR-CODE-02", Category = "CodeQuality", Description = "All entity fields must be mapped in DTOs", ValidationRule = "dto_field_coverage" },
        new() { Id = "NFR-TEST-01", Category = "Testing", Description = "All services must have unit tests with real assertions", ValidationRule = "no_stub_assertions" },
    ];

    private static List<string> InferFeatureTags(MicroserviceDefinition svc, string entity) =>
        [svc.Name, svc.ShortName, entity];

    private static string ToKebabCase(string name) =>
        KebabRegex().Replace(name, "-$1").ToLowerInvariant().TrimStart('-');

    private static string ToSnakeCase(string name) =>
        KebabRegex().Replace(name, "_$1").ToLowerInvariant().TrimStart('_');

    [GeneratedRegex(@"public\s+(?<type>[\w<>,\s\?]+)\s+(?<name>\w+)\s*\{[^}]*\}\s*(?:=\s*(?<default>[^;]+);)?")]
    private static partial Regex PropertyRegex();

    [GeneratedRegex(@"(?<=[a-z])([A-Z])")]
    private static partial Regex KebabRegex();
}
