namespace GNex.Core.Models;

/// <summary>
/// LLM-derived domain profile populated by <c>PromptGeneratorAgent</c>.
/// Contains domain-specific actors, personas, compliance frameworks, integration
/// patterns, and generated system prompts that downstream agents consume
/// instead of relying on hardcoded domain knowledge.
/// </summary>
public sealed class DomainProfile
{
    // ── Identity ──

    /// <summary>Canonical domain name (e.g. "Healthcare", "FinTech", "E-Commerce").</summary>
    public string Domain { get; set; } = string.Empty;

    /// <summary>Full domain description from pipeline config or LLM enrichment.</summary>
    public string DomainDescription { get; set; } = string.Empty;

    // ── Actors & Personas ──

    /// <summary>LLM-derived primary actors/personas for this domain (e.g. "Physician", "Trader", "Shopper").</summary>
    public List<DomainActor> Actors { get; set; } = [];

    // ── Compliance ──

    /// <summary>Applicable compliance frameworks for this domain (e.g. HIPAA, SOC2, PCI-DSS, GDPR).</summary>
    public List<ComplianceFramework> ComplianceFrameworks { get; set; } = [];

    // ── Integration patterns ──

    /// <summary>Domain-specific integration protocols/standards (e.g. FHIR, HL7, FIX, EDI).</summary>
    public List<IntegrationPattern> IntegrationPatterns { get; set; } = [];

    // ── Sensitive data ──

    /// <summary>Domain-specific sensitive/regulated field names (e.g. PHI fields for healthcare, PII for fintech).</summary>
    public List<string> SensitiveFieldPatterns { get; set; } = [];

    /// <summary>Data classification label (e.g. "PHI", "PII", "PCI").</summary>
    public string SensitiveDataClassification { get; set; } = "PII";

    // ── Domain vocabulary ──

    /// <summary>
    /// Domain glossary — canonical term → definition mapping.
    /// Agents use this to ensure consistent terminology in generated code,
    /// documentation, and API naming (e.g. "Encounter" not "Visit" in healthcare).
    /// </summary>
    public Dictionary<string, string> DomainGlossary { get; set; } = new(StringComparer.OrdinalIgnoreCase);

    // ── Business rules ──

    /// <summary>
    /// Domain-specific business rules/invariants that code-gen agents must enforce.
    /// E.g. "An encounter cannot be closed while active orders exist" or
    /// "A trade must have a settlement date within T+2".
    /// </summary>
    public List<string> BusinessRules { get; set; } = [];

    // ── Quality attributes ──

    /// <summary>
    /// Domain-specific quality attributes / non-functional requirements.
    /// E.g. "Max 200ms P95 latency for order placement" or "99.99% uptime for trading engine".
    /// Performance, LoadTest, and Observability agents read these.
    /// </summary>
    public List<string> QualityAttributes { get; set; } = [];

    // ── Domain events ──

    /// <summary>
    /// Canonical domain events for event-driven architectures.
    /// E.g. "PatientAdmitted", "OrderPlaced", "TradeSettled".
    /// IntegrationAgent and event catalog generation read these.
    /// </summary>
    public List<DomainEvent> DomainEvents { get; set; } = [];

    // ── Requirement tags ──

    /// <summary>Domain-relevant requirement tags used for coverage checks (e.g. Patient/Encounter for healthcare, Order/Payment for e-commerce).</summary>
    public List<string> DomainRequirementTags { get; set; } = [];

    // ── Generated prompts ──

    /// <summary>
    /// Agent-specific system prompts generated by PromptGeneratorAgent.
    /// Key = AgentType name (e.g. "HipaaCompliance", "BrdGenerator").
    /// Value = generated system prompt string.
    /// Agents check this dictionary first; if a prompt exists, they use it
    /// instead of their default/hardcoded prompt.
    /// </summary>
    public Dictionary<string, string> AgentPrompts { get; set; } = new(StringComparer.OrdinalIgnoreCase);

    // ── ER diagram fallback ──

    /// <summary>LLM-generated fallback ER diagram (Mermaid) when no domain model exists yet.</summary>
    public string FallbackErDiagram { get; set; } = string.Empty;

    // ── Convenience ──

    /// <summary>Get actor names as a simple list.</summary>
    public IReadOnlyList<string> ActorNames => Actors.Select(a => a.Name).ToList();

    /// <summary>Check if a compliance framework is applicable.</summary>
    public bool RequiresCompliance(string frameworkName)
        => ComplianceFrameworks.Any(c => c.Name.Contains(frameworkName, StringComparison.OrdinalIgnoreCase));
}

/// <summary>A domain actor/persona with role description and typical use cases.</summary>
public sealed class DomainActor
{
    public string Name { get; set; } = string.Empty;
    public string Role { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public List<string> TypicalUseCases { get; set; } = [];
}

/// <summary>A compliance framework applicable to the domain.</summary>
public sealed class ComplianceFramework
{
    /// <summary>Framework name (e.g. "HIPAA", "SOC2", "PCI-DSS", "GDPR").</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Whether this framework is universally required (like SOC2) or domain-specific (like HIPAA).</summary>
    public bool IsUniversal { get; set; }

    /// <summary>Key clauses/sections relevant to this project.</summary>
    public List<string> KeyClauses { get; set; } = [];

    /// <summary>LLM-generated compliance scanning prompt for this framework.</summary>
    public string ScanPrompt { get; set; } = string.Empty;
}

/// <summary>A canonical domain event for event-driven architecture.</summary>
public sealed class DomainEvent
{
    /// <summary>Event name in PascalCase (e.g. "OrderPlaced", "PatientAdmitted").</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>The aggregate/entity that produces this event.</summary>
    public string Source { get; set; } = string.Empty;

    /// <summary>Description of when/why this event is raised.</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Key payload fields carried by this event.</summary>
    public List<string> PayloadFields { get; set; } = [];
}

/// <summary>An integration protocol/standard relevant to the domain.</summary>
public sealed class IntegrationPattern
{
    /// <summary>Protocol/standard name (e.g. "FHIR R4", "HL7 v2", "FIX 4.4", "EDI X12").</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>When this protocol applies — always or conditional on certain requirements.</summary>
    public string Applicability { get; set; } = string.Empty;

    /// <summary>LLM-generated adapter code or description for this protocol.</summary>
    public string AdapterDescription { get; set; } = string.Empty;
}
