namespace GNex.Core.Models;

public enum WorkItemType { Epic, UserStory, UseCase, Task, Bug }

public enum WorkItemStatus
{
    New,        // Just generated by the expander
    InQueue,    // Queued for development iteration
    Received,   // Claimed by an agent, awaiting processing start
    InProgress, // Agent actively working on this item
    Completed,  // Artifacts generated and reviewed
    Failed,     // Agent failed processing this item (will retry or return to backlog)
    Blocked,    // Dependency not met

    // Legacy aliases — kept so existing code referencing UnderDev keeps compiling
    UnderDev = InProgress
}

/// <summary>
/// Tracks how well a requirement is covered by generated artifacts.
/// </summary>
public enum CoverageStatus
{
    NotAssessed,    // Haven't checked yet
    NotStarted,     // No artifacts match this requirement
    Partial,        // Some artifacts exist but acceptance criteria not fully met
    Covered,        // All acceptance criteria have matching artifacts
    GapIdentified   // Analyzer found specific missing pieces
}

public sealed class ExpandedRequirement
{
    public string Id { get; init; } = string.Empty;
    /// <summary>The project this work item belongs to. Null for legacy/global runs.</summary>
    public string? ProjectId { get; set; }
    public string ParentId { get; init; } = string.Empty;
    public string SourceRequirementId { get; init; } = string.Empty;
    public WorkItemType ItemType { get; init; }
    public WorkItemStatus Status { get; set; } = WorkItemStatus.New;
    public string Title { get; init; } = string.Empty;
    public string Description { get; init; } = string.Empty;
    public string Module { get; init; } = string.Empty;
    public int Priority { get; set; }
    public int Iteration { get; set; }
    public List<string> AcceptanceCriteria { get; init; } = [];
    public List<string> DependsOn { get; init; } = [];
    public List<string> Tags { get; init; } = [];
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
    public DateTimeOffset? StartedAt { get; set; }
    public DateTimeOffset? CompletedAt { get; set; }
    /// <summary>Which agent is currently working on (or completed) this item.</summary>
    public string AssignedAgent { get; set; } = string.Empty;

    /// <summary>Number of times this item has been retried after failure.</summary>
    public int RetryCount { get; set; }

    /// <summary>Last agent that failed processing this item (for diagnostics).</summary>
    public string LastFailedAgent { get; set; } = string.Empty;

    // ── Epic template fields ──
    /// <summary>Brief "elevator pitch" of what this epic achieves.</summary>
    public string Summary { get; set; } = string.Empty;
    /// <summary>Why are we doing this? Business justification.</summary>
    public string BusinessValue { get; set; } = string.Empty;
    /// <summary>Measurable outcomes (e.g., "Users can log in via MFA with &lt; 2s latency").</summary>
    public List<string> SuccessCriteria { get; set; } = [];
    /// <summary>What is included — and importantly, what is NOT included.</summary>
    public string Scope { get; set; } = string.Empty;

    // ── User Story template fields ──
    /// <summary>Story points estimate: 1, 2, 3, 5, or 8.</summary>
    public int StoryPoints { get; set; }
    /// <summary>Labels (e.g., Frontend, API, Design).</summary>
    public List<string> Labels { get; set; } = [];

    // ── Use Case template fields ──
    /// <summary>The actor interacting with the system.</summary>
    public string Actor { get; set; } = string.Empty;
    /// <summary>Pre-conditions that must hold before the use case starts.</summary>
    public string Preconditions { get; set; } = string.Empty;
    /// <summary>Main success scenario — numbered steps.</summary>
    public List<string> MainFlow { get; set; } = [];
    /// <summary>Alternative / exception flows.</summary>
    public string AlternativeFlows { get; set; } = string.Empty;
    /// <summary>Post-conditions after successful completion.</summary>
    public string Postconditions { get; set; } = string.Empty;

    // ── Task template fields ──
    /// <summary>Implementation-specific technical notes (e.g., "Use Redis for token storage, 15-min TTL").</summary>
    public string TechnicalNotes { get; set; } = string.Empty;
    /// <summary>Definition of Done checklist items.</summary>
    public List<string> DefinitionOfDone { get; set; } = [];

    // ── Bug Report template fields ──
    /// <summary>Severity: Blocker, Critical, Major, Minor.</summary>
    public string Severity { get; set; } = string.Empty;
    /// <summary>Environment where bug occurs (e.g., "iOS 17.4, Safari, Production").</summary>
    public string Environment { get; set; } = string.Empty;
    /// <summary>Numbered steps to reproduce the bug.</summary>
    public List<string> StepsToReproduce { get; set; } = [];
    /// <summary>What should happen.</summary>
    public string ExpectedResult { get; set; } = string.Empty;
    /// <summary>What actually happens.</summary>
    public string ActualResult { get; set; } = string.Empty;

    // ── Gap-analysis fields (populated by RequirementAnalyzerAgent) ──
    /// <summary>Coverage assessment after artifact analysis.</summary>
    public CoverageStatus Coverage { get; set; } = CoverageStatus.NotAssessed;
    /// <summary>Specific gaps identified (e.g. "Missing RLS policy", "No unit tests for UpdateClaim").</summary>
    public List<string> IdentifiedGaps { get; set; } = [];
    /// <summary>Artifacts that implement (fully or partially) this requirement.</summary>
    public List<string> MatchingArtifactPaths { get; set; } = [];
    /// <summary>IDs of requirements that must be completed before this one can start.</summary>
    public List<string> ResolvedDependencyChain { get; set; } = [];
    /// <summary>Services/entities this requirement touches — guides downstream code-gen agents.</summary>
    public List<string> AffectedServices { get; set; } = [];
    /// <summary>Detailed specification for downstream agents (DB schema hints, API contracts, validation rules).</summary>
    public string DetailedSpec { get; set; } = string.Empty;
    /// <summary>Source: which agent created this item (Expander, Analyzer, Backlog).</summary>
    public string ProducedBy { get; set; } = string.Empty;

    // ── DOD verification tracking ──
    /// <summary>Per-DOD-item verification status. Key = DOD text, Value = true if verified.</summary>
    public Dictionary<string, bool> DodVerificationStatus { get; set; } = new();
    /// <summary>Whether all DOD items have been verified by the DodVerificationAgent.</summary>
    public bool DodVerified { get; set; }
    /// <summary>Reasons why specific DOD items failed verification.</summary>
    public List<string> DodVerificationNotes { get; set; } = [];
}
