using FluentAssertions;
using HmsAgents.Agents.Orchestrator;
using HmsAgents.Core.Enums;
using HmsAgents.Core.Interfaces;
using HmsAgents.Core.Models;
using Microsoft.Extensions.Logging;
using Moq;

namespace HmsAgents.Tests;

public class OrchestratorTests
{
    private readonly Mock<IArtifactWriter> _writerMock = new();
    private readonly Mock<IPipelineEventSink> _sinkMock = new();
    private readonly Mock<IAuditLogger> _auditMock = new();
    private readonly Mock<IHumanGate> _humanGateMock = new();
    private readonly Mock<ILogger<AgentOrchestrator>> _loggerMock = new();

    private PipelineConfig CreateConfig() => new()
    {
        RequirementsPath = Path.Combine(Path.GetTempPath(), "hms-test-reqs"),
        OutputPath = Path.Combine(Path.GetTempPath(), "hms-test-out"),
        SpinUpDocker = false,
        ExecuteDdl = false
    };

    private static Mock<IAgent> CreateAgentMock(AgentType type, string name, bool success = true, int artifactCount = 3)
    {
        var mock = new Mock<IAgent>();
        mock.Setup(a => a.Type).Returns(type);
        mock.Setup(a => a.Name).Returns(name);
        mock.Setup(a => a.ExecuteAsync(It.IsAny<AgentContext>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((AgentContext ctx, CancellationToken _) =>
            {
                ctx.AgentStatuses[type] = success ? AgentStatus.Completed : AgentStatus.Failed;
                var artifacts = Enumerable.Range(0, artifactCount).Select(i => new CodeArtifact
                {
                    Layer = ArtifactLayer.Database,
                    RelativePath = $"{name}/{i}.cs",
                    FileName = $"{i}.cs",
                    Content = $"// Generated by {name}",
                    ProducedBy = type
                }).ToList();
                ctx.Artifacts.AddRange(artifacts);
                return new AgentResult
                {
                    Agent = type,
                    Success = success,
                    Summary = success ? $"{name} ok" : $"{name} failed",
                    Artifacts = artifacts
                };
            });
        return mock;
    }

    [Fact]
    public async Task RunPipeline_AllAgentsSucceed_CompletesSuccessfully()
    {
        // Arrange
        var reqsDir = CreateConfig().RequirementsPath;
        Directory.CreateDirectory(reqsDir);
        File.WriteAllText(Path.Combine(reqsDir, "test.md"), "# REQ-001\nTest requirement");

        var agents = new List<IAgent>
        {
            CreateAgentMock(AgentType.RequirementsReader, "ReqReader").Object,
            CreateAgentMock(AgentType.Database, "Database").Object,
            CreateAgentMock(AgentType.ServiceLayer, "ServiceLayer").Object,
            CreateAgentMock(AgentType.Application, "Application").Object,
            CreateAgentMock(AgentType.Integration, "Integration").Object,
            CreateAgentMock(AgentType.Testing, "Testing").Object,
            CreateAgentMock(AgentType.Review, "Review").Object,
            CreateAgentMock(AgentType.Supervisor, "Supervisor").Object,
        };

        var orchestrator = new AgentOrchestrator(agents, _writerMock.Object, _sinkMock.Object, _auditMock.Object, _humanGateMock.Object, _loggerMock.Object);

        // Act
        var result = await orchestrator.RunPipelineAsync(CreateConfig());

        // Assert
        result.CompletedAt.Should().NotBeNull();
        result.Artifacts.Should().NotBeEmpty();
        result.AgentStatuses.Values.Where(s => s == AgentStatus.Completed).Should().HaveCountGreaterThan(0);
    }

    [Fact]
    public async Task RunPipeline_AgentFails_RunsHealCycleAndRetries()
    {
        // Arrange
        var dbCallCount = 0;
        var bugFixCalled = false;
        var perfCalled = false;
        var reviewCalled = false;

        var failingAgent = new Mock<IAgent>();
        failingAgent.Setup(a => a.Type).Returns(AgentType.Database);
        failingAgent.Setup(a => a.Name).Returns("Database");
        failingAgent.Setup(a => a.ExecuteAsync(It.IsAny<AgentContext>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((AgentContext ctx, CancellationToken _) =>
            {
                dbCallCount++;
                ctx.AgentStatuses[AgentType.Database] = AgentStatus.Failed;
                return new AgentResult { Agent = AgentType.Database, Success = false, Summary = "DB failed", Errors = ["Connection refused"] };
            });

        var bugFixAgent = new Mock<IAgent>();
        bugFixAgent.Setup(a => a.Type).Returns(AgentType.BugFix);
        bugFixAgent.Setup(a => a.Name).Returns("BugFix");
        bugFixAgent.Setup(a => a.ExecuteAsync(It.IsAny<AgentContext>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((AgentContext ctx, CancellationToken _) =>
            {
                bugFixCalled = true;
                ctx.AgentStatuses[AgentType.BugFix] = AgentStatus.Completed;
                return new AgentResult { Agent = AgentType.BugFix, Success = true, Summary = "BugFix applied" };
            });

        var perfAgent = new Mock<IAgent>();
        perfAgent.Setup(a => a.Type).Returns(AgentType.Performance);
        perfAgent.Setup(a => a.Name).Returns("Performance");
        perfAgent.Setup(a => a.ExecuteAsync(It.IsAny<AgentContext>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((AgentContext ctx, CancellationToken _) =>
            {
                perfCalled = true;
                ctx.AgentStatuses[AgentType.Performance] = AgentStatus.Completed;
                return new AgentResult { Agent = AgentType.Performance, Success = true, Summary = "Perf ok" };
            });

        var reviewAgent = new Mock<IAgent>();
        reviewAgent.Setup(a => a.Type).Returns(AgentType.Review);
        reviewAgent.Setup(a => a.Name).Returns("Review");
        reviewAgent.Setup(a => a.ExecuteAsync(It.IsAny<AgentContext>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((AgentContext ctx, CancellationToken _) =>
            {
                reviewCalled = true;
                ctx.AgentStatuses[AgentType.Review] = AgentStatus.Completed;
                return new AgentResult { Agent = AgentType.Review, Success = true, Summary = "Review ok" };
            });

        var agents = new List<IAgent>
        {
            CreateAgentMock(AgentType.RequirementsReader, "ReqReader").Object,
            failingAgent.Object,
            bugFixAgent.Object,
            perfAgent.Object,
            reviewAgent.Object,
            CreateAgentMock(AgentType.Supervisor, "Supervisor").Object,
        };

        var orchestrator = new AgentOrchestrator(agents, _writerMock.Object, _sinkMock.Object, _auditMock.Object, _humanGateMock.Object, _loggerMock.Object);

        // Act
        var result = await orchestrator.RunPipelineAsync(CreateConfig());

        // Assert — DB retried, heal cycle ran (BugFix→Performance→Review)
        dbCallCount.Should().BeGreaterThan(1, "orchestrator should retry failed agents");
        bugFixCalled.Should().BeTrue("BugFix should run in heal cycle to fix root cause");
        perfCalled.Should().BeTrue("Performance should check the fix");
        reviewCalled.Should().BeTrue("Review should validate the fix");
        // Self-healing marks exhausted agents as Failed so items can be re-queued
        result.AgentStatuses[AgentType.Database].Should().Be(AgentStatus.Failed);
    }

    [Fact]
    public async Task RunPipeline_FailedStage_StillRunsSupervisor()
    {
        // Arrange
        var supervisorCalled = false;
        var supervisorMock = new Mock<IAgent>();
        supervisorMock.Setup(a => a.Type).Returns(AgentType.Supervisor);
        supervisorMock.Setup(a => a.Name).Returns("Supervisor");
        supervisorMock.Setup(a => a.ExecuteAsync(It.IsAny<AgentContext>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((AgentContext ctx, CancellationToken _) =>
            {
                supervisorCalled = true;
                ctx.AgentStatuses[AgentType.Supervisor] = AgentStatus.Completed;
                return new AgentResult { Agent = AgentType.Supervisor, Success = true, Summary = "Diagnosed" };
            });

        var failingAgent = new Mock<IAgent>();
        failingAgent.Setup(a => a.Type).Returns(AgentType.Database);
        failingAgent.Setup(a => a.Name).Returns("Database");
        failingAgent.Setup(a => a.ExecuteAsync(It.IsAny<AgentContext>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((AgentContext ctx, CancellationToken _) =>
            {
                ctx.AgentStatuses[AgentType.Database] = AgentStatus.Failed;
                return new AgentResult { Agent = AgentType.Database, Success = false, Errors = ["fail"] };
            });

        var agents = new List<IAgent>
        {
            CreateAgentMock(AgentType.RequirementsReader, "ReqReader").Object,
            failingAgent.Object,
            supervisorMock.Object
        };

        var orchestrator = new AgentOrchestrator(agents, _writerMock.Object, _sinkMock.Object, _auditMock.Object, _humanGateMock.Object, _loggerMock.Object);

        // Act
        await orchestrator.RunPipelineAsync(CreateConfig());

        // Assert
        supervisorCalled.Should().BeTrue("supervisor should run even when pipeline fails to diagnose issues");
    }

    [Fact]
    public async Task RunPipeline_EmitsEventsForEveryAgent()
    {
        // Arrange
        var events = new List<PipelineEvent>();
        _sinkMock.Setup(s => s.OnEventAsync(It.IsAny<PipelineEvent>(), It.IsAny<CancellationToken>()))
            .Callback<PipelineEvent, CancellationToken>((e, _) => events.Add(e))
            .Returns(Task.CompletedTask);

        var agents = new List<IAgent>
        {
            CreateAgentMock(AgentType.RequirementsReader, "ReqReader").Object,
            CreateAgentMock(AgentType.Database, "Database").Object,
            CreateAgentMock(AgentType.Supervisor, "Supervisor").Object,
        };

        var orchestrator = new AgentOrchestrator(agents, _writerMock.Object, _sinkMock.Object, _auditMock.Object, _humanGateMock.Object, _loggerMock.Object);

        // Act
        await orchestrator.RunPipelineAsync(CreateConfig());

        // Assert — should have Running + Completed events for each agent
        events.Where(e => e.Status == AgentStatus.Running).Should().HaveCountGreaterOrEqualTo(3);
        events.Where(e => e.Status == AgentStatus.Completed).Should().HaveCountGreaterOrEqualTo(3);
    }

    [Fact]
    public async Task RunPipeline_WritesArtifactsToDisk_WhenOutputPathSet()
    {
        // Arrange
        var agents = new List<IAgent>
        {
            CreateAgentMock(AgentType.RequirementsReader, "ReqReader").Object,
            CreateAgentMock(AgentType.Supervisor, "Supervisor").Object,
        };

        var orchestrator = new AgentOrchestrator(agents, _writerMock.Object, _sinkMock.Object, _auditMock.Object, _humanGateMock.Object, _loggerMock.Object);
        var config = CreateConfig();

        // Act
        var result = await orchestrator.RunPipelineAsync(config);

        // Assert
        if (result.Artifacts.Count > 0)
        {
            _writerMock.Verify(w => w.WriteAllAsync(It.IsAny<IEnumerable<CodeArtifact>>(), config.OutputPath, It.IsAny<CancellationToken>()), Times.Once);
        }
    }

    [Fact]
    public void GetCurrentContext_ReturnsNull_BeforePipelineRun()
    {
        var agents = new List<IAgent>();
        var orchestrator = new AgentOrchestrator(agents, _writerMock.Object, _sinkMock.Object, _auditMock.Object, _humanGateMock.Object, _loggerMock.Object);
        orchestrator.GetCurrentContext().Should().BeNull();
    }

    [Fact]
    public void RelevantTaskAgents_UsesDescriptionText_ForRouting()
    {
        var item = new ExpandedRequirement
        {
            Id = "TASK-001",
            ItemType = WorkItemType.Task,
            Title = "Implement persistence",
            Description = "Create SQL migration and update DbContext mappings for admissions",
            Tags = []
        };

        var method = typeof(AgentOrchestrator).GetMethod("GetRelevantTaskAgents", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
        method.Should().NotBeNull();

        var result = method!.Invoke(null, [item]) as List<string>;

        result.Should().NotBeNull();
        result!.Should().Contain(AgentType.Database.ToString());
    }
}
