namespace HmsAgents.Core.Enums;

public enum AgentType
{
    Orchestrator,
    RequirementsReader,
    Database,
    ServiceLayer,
    Application,
    Integration,
    Review,
    Testing,
    Supervisor,
    BugFix,
    Performance,
    Security,
    HipaaCompliance,
    Soc2Compliance,
    AccessControl,
    Observability,
    Infrastructure,
    ApiDocumentation,
    RequirementsExpander,
    Backlog,
    Deploy,
    RequirementAnalyzer,
    Build,
    Monitor,
    Migration,
    CodeQuality,
    DependencyAudit,
    Refactoring,
    Configuration,
    UiUx,
    LoadTest
}
